/*
 * Gladiatus Crazy Addon Translation
 * Generated by GCA translation generator [Beta]
 * [Translation completed by 22%]
 * Name : Albanian
 * Code : [none]
 * Tag  : sq
 * Translator: Besmir Sadiku [s_besmir@hotmail.com]
 */

gca_languages['sq'] = {
	name : 'Shqip',
	translator : "Besmir Sadiku [s_besmir@hotmail.com]",
	locale : {
		description : "Shtesa më e mirë për Gladiatus!",
		write_private_message : "Shkruaj mesazh privat",
		write_guild_message : "Shkruaj mesazh shoqërisë",
		send : "Dërgo",
		exclude_me : "Më përjashto",
		go_to_guilds_medic_center : "Shko në qendrën mjekësore të shoqërisë",
		go_to_guilds_market : "Shko në tregun e shoqërisë",
		go_to_guilds_storage : "Shko në depon e shoqërisë",
		go_to_guilds_bank : "Shko në bankën e shoqërisë",
		donate_all_your_gold : "Dhuro të gjithë arin tuaj",
		go_to_guilds_war_camp : "Shko në kampin ushtarak të shoqërisë",
		go_to_guilds_jail : "Shko në burgun e shoqërisë",
		go_to_guilds_library : "Shko në librarinë e shoqërisë",
		go_to_simulator : "Shko tek simulatori",
		display_my_stats : "Shfaq statistikat e mia",
		display_online_players : "Shfaq lojtarët aktiv",
		quest_new : "E re",
		quest_full : "E plotë",
		weapon_down : "Arma juaj është larguar!",
		leveling_stats : "Përvoja statistika",
		today_experience : "Përvoja ditore",
		days7_experience : "Përvoja 7 ditore",
		avarage_experiance_per_day : "Përvoja mesatare për ditë",
		days_left_to_level_up : "Ditët e mbetura për nivel më të lartë",
		gold_after_enable : "Ari mbas lejimit",
		lost_points : "Pikët e humbura",
		points_to_heal : "Pikët për shërim",
		life_after_heal : "Jeta mbas shërimit",
		guild_life : "Jetëgjatësia e shoqërisë",
		difference : "Diferenca",
		total : "Totali",
		add_all_gold : "Shko tërë arin",
		attacks : "Sulmet",
		defences : "Mbrojtjet",
		friendly : "Miqësor",
		pending_guild_application : "Një aplikacion i shoqërisë është në pritje!",
		calculate_guild_upgrade : "Llogaritë ngritjen e shoqërisë",
		include : "Përfshij",
		custom_amount : "Shuma e caktuar",
		gold_per_player : "Ari për lojtar",
		target_gold : "Ari "
	}
}

