/*
 * Gladiatus Crazy Addon Translation
 * Generated by GCA translation generator [Beta]
 * [Translation completed by 12%]
 * Name : Slovenian
 * Code : [none]
 * Tag  : sl
 * Translator: TANKISTA33@azet.sk
 */

gca_languages['sl'] = {
	name : 'Slovenčina ',
	translator : "TANKISTA33@azet.sk",
	locale : {
		description : "Najbláznivejšie add-on pre Gladiatus vôbec!",
		write_private_message : "Napíšte súkromnú správu",
		write_guild_message : "Napíšte gildovnú správu",
		send : "Odoslať",
		exclude_me : "Vylúčiť ma",
		go_to_guilds_medic_center : "Prejsť na percentra gildy",
		go_to_guilds_market : "Prejsť na trh gildy",
		go_to_guilds_storage : "Prejsť do slkadu gildy",
		go_to_guilds_bank : "Prejsť do gildovnej banky",
		donate_all_your_gold : "Darujte všetko zlato",
		go_to_guilds_war_camp : "Prejsť na tábor vojny gildy",
		go_to_guilds_jail : "Ísť do väzenia gildy",
		go_to_guilds_library : "Choďte do knižnice gildy",
		go_to_simulator : "Prejsť na simulátore",
		display_my_stats : "Zobrazenie Moje štatistiky",
		display_online_players : "Pozrieť online hráčov",
		quest_new : "Nový",
		quest_full : "Plný",
		weapon_down : "Vaša zbraň je odstránená!",
		leveling_stats : "Skúsenosti štatistik",
		today_experience : "Dnešné skúsenosti",
		days7_experience : "7 dnove skúsenosťi"
	}
}

gca_locale.active = "sl";
